# Generated by Django 5.0.4 on 2024-05-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaisanpham',
            name='TrangThai',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sanpham',
            name='TrangThai',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
