# Generated by Django 5.0.4 on 2024-05-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_loaisanpham_trangthai_sanpham_trangthai'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='DiaChiGiao',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hoadon',
            name='SDT',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
