# Generated by Django 5.0.4 on 2024-05-24 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_hoadon_diachigiao_hoadon_sdt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoadon',
            name='MaKH',
        ),
    ]
