# Generated by Django 5.0.4 on 2024-05-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_hoadon_makh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='Tong',
            field=models.BigIntegerField(null=True),
        ),
    ]
