# Generated by Django 5.1.1 on 2024-10-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_hoadon_tong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaisanpham',
            name='TrangThai',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='HinhAnh',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='TrangThai',
            field=models.SmallIntegerField(default=1),
        ),
    ]
